### ISSUE TITLE
Tidying the data up

### ISSUE THREAD

**Issue by zelima** [gsilvapt/historical-gdp#1]
I would suggest removing all the rows that have no data , e.g. First two rows, plus first five odd rows that don't seem to have any data.

Also, I'd name the first column Year.

I'm not sure about this one, but I'll say: Maybe It would be better to have 3 columns total and data would look something like this:
```
Country,Year,GDP 
Austria,1,213
Austria,1000,298
...
Zimbabwe,2008,50 973 935
```
But as I said I'm not sure, Think it'll be better to consult with @rgrp

**Comment by gsilvapt** [comment]
Hi @zelima!

Thanks again for contributing. Yes, these datasets have some weird rows. I asked about that in the [datasets/registry](https://github.com/datasets/registry/issues/101#issuecomment-215579963) issue tracking. We can post these online and then comeback to fix these or work on this simultaneously, as you guys prefer. I was trying to get completely aware of the process of creating and publishing datasets and then work on the data's quality but if this is requirement (which would be logical) then I can take care of this very soon.

**Comment by gsilvapt** [comment]
Done for all three datasets.
