### ISSUE TITLE
Fixing the datapackage.json

### ISSUE THREAD

**Issue by zelima** [gsilvapt/historical-gdp#2]
Right now schema points to wrong fields, so [vewer](http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fgsilvapt%2Fhistorical-gdp) can't show the correct data.
I would suggest to name fields correctly, in your case it should be something like
```
 "schema": {
        "fields": [
          {
            "name": "Year",
            "type": "date",
            "description": ""
          },
          {
            "name": "Austria",
            "type": "number",
            "description": ""
          },
          ...
         {
          "name": "column name"
          "type": "the type that column data is (string, number or date)"
         "description": 'little description about data (optional)'
         }
       ]
     }
```

**Comment by gsilvapt** [comment]
Right. I first saw this and thought this was related with the fact that there are so many blank rows. Okay, it seems I have to first remove those blank spots and then re-do the process.

Thanks!
