### ISSUE TITLE
Moving data to data/ directory

### ISSUE THREAD

**Issue by zelima** [gsilvapt/historical-gdp#3]
The data (CSV file) should be in data directory. In this case - data/gdp.csv

And also, I'd suggest to name csv file historical-gdp.csv - Think there should already be data named gdp.csv.

**Comment by gsilvapt** [comment]
I didn't put it in a folder like that because the guide didn't mention that. I used to do it that way before, with another initiative. Will take care of these now.

**Comment by zelima** [comment]
That's ok, I suggest this way cause most of other datasets look like that.
If you think it's better to keep in this or other way you can always discuss it Rufus or other members of community. :)

**Comment by gsilvapt** [comment]
It is fine. I'm here to comply with the others so no need to argue over that :P

**Comment by gsilvapt** [comment]
Done in all of them.
